name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
        description: 'Name of the service to build (backend, billing, frontend, outbound)'
      dockerfile_path:
        required: true
        type: string
        description: 'Path to the Dockerfile'
      build_context:
        required: true
        type: string
        description: 'Build context directory'
      image_name:
        required: true
        type: string
        description: 'Docker image name (e.g., simple-relay, simple-billing)'
      region:
        required: false
        type: string
        default: 'us-central1'
        description: 'GCP region for container registry'
      build_args:
        required: false
        type: string
        default: ''
        description: 'Additional build arguments (space-separated, e.g., "ARG1=value1 ARG2=value2")'
      source_repo:
        required: false
        type: string
        default: ''
        description: 'Source repository to checkout (defaults to caller repo)'
      source_ref:
        required: false
        type: string
        default: ''
        description: 'Source ref to checkout (defaults to caller ref)'
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
    outputs:
      image_tag:
        description: 'The tag of the built image'
        value: ${{ jobs.docker-build.outputs.image_tag }}

jobs:
  docker-build:
    name: Build and Push ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source_repo || github.repository }}
        ref: ${{ inputs.source_ref || github.sha }}
        token: ${{ github.token }}

    - name: Set image tag
      id: set-tag
      run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Docker Auth
      uses: 'docker/login-action@v3'
      with:
        registry: ${{ inputs.region }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build and Push Container
      working-directory: ${{ inputs.build_context }}
      run: |
        BUILD_ARGS=""
        if [ -n "${{ inputs.build_args }}" ]; then
          for arg in ${{ inputs.build_args }}; do
            BUILD_ARGS="$BUILD_ARGS --build-arg $arg"
          done
        fi
        
        IMAGE_URI="${{ inputs.region }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simple-relay/${{ inputs.image_name }}:${{ github.sha }}"
        
        docker build --platform linux/amd64 \
          -f ${{ inputs.dockerfile_path }} \
          $BUILD_ARGS \
          -t "$IMAGE_URI" \
          .
        
        docker push "$IMAGE_URI"
        
        echo "Built and pushed: $IMAGE_URI"

