name: Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      simple_relay_ref:
        description: 'Branch or tag from simple-relay to deploy'
        required: false
        default: 'main'
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: production
      simple_relay_ref: ${{ inputs.simple_relay_ref || 'main' }}
    secrets: inherit

