name: Reusable Terraform Deployment

on:
  workflow_call:
    inputs:
      deploy_environment:
        required: true
        type: string
        description: 'Environment to deploy to (production or staging)'
      terraform_version:
        required: false
        type: string
        default: '1.5.0'
        description: 'Terraform version to use'
      terraform_directory:
        required: false
        type: string
        default: './terraform'
        description: 'Directory containing Terraform files'
      image_tag:
        required: true
        type: string
        description: 'Docker image tag to deploy'
      region:
        required: false
        type: string
        default: 'us-central1'
        description: 'GCP region'
      source_repo:
        required: false
        type: string
        default: ''
        description: 'Source repository to checkout (defaults to caller repo)'
      source_ref:
        required: false
        type: string
        default: ''
        description: 'Source ref to checkout (defaults to caller ref)'
      plan_only:
        required: false
        type: boolean
        default: false
        description: 'Only run terraform plan, do not apply'
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
      API_BASE_URL:
        required: true
      OFFICIAL_BASE_URL:
        required: true
      API_SECRET_KEY:
        required: true
      RESEND_API_KEY_PRODUCTION:
        required: false
      RESEND_API_KEY_STAGING:
        required: false
      RESEND_FROM_EMAIL:
        required: true
      COOKIE_SECRET_PRODUCTION:
        required: false
      COOKIE_SECRET_STAGING:
        required: false
      WECHAT_APP_ID:
        required: true
      WECHAT_MCH_ID:
        required: true
      WECHAT_MCH_API_V3_KEY:
        required: true
      WECHAT_MCH_SERIAL_NO:
        required: true
      WECHAT_NOTIFY_URL_PRODUCTION:
        required: false
      WECHAT_NOTIFY_URL_STAGING:
        required: false
      WECHAT_MCH_PRIVATE_KEY_BASE64:
        required: true
      WECHAT_PAY_PUBLIC_KEY_BASE64:
        required: true
      WECHAT_PAY_PUBLIC_KEY_ID:
        required: true
      WECHAT_PLATFORM_CERT_BASE64:
        required: true
      WECHAT_PLATFORM_CERT_SERIAL_NO:
        required: true

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_environment }}
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source_repo || github.repository }}
        ref: ${{ inputs.source_ref || github.sha }}
        token: ${{ github.token }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init \
          -backend-config="bucket=simple-relay-${{ inputs.deploy_environment }}" \
          -backend-config="prefix=terraform-state"

    - name: Terraform Validate
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform validate

    - name: Terraform Plan
      working-directory: ${{ inputs.terraform_directory }}
      env:
        TF_VAR_api_base_url: ${{ secrets.API_BASE_URL }}
        TF_VAR_official_base_url: ${{ secrets.OFFICIAL_BASE_URL }}
        TF_VAR_image_tag: ${{ inputs.image_tag }}
        TF_VAR_service_name: simple-relay
        TF_VAR_billing_service_name: simple-relay-billing
        TF_VAR_frontend_service_name: simple-relay-frontend
        TF_VAR_outbound_service_1_name: simple-relay-outbound-1
        TF_VAR_outbound_service_2_name: simple-relay-outbound-2
        TF_VAR_firestore_database_name: simple-relay-db
        TF_VAR_deploy_environment: ${{ inputs.deploy_environment }}
        TF_VAR_api_secret_key: ${{ secrets.API_SECRET_KEY }}
        TF_VAR_resend_api_key: ${{ inputs.deploy_environment == 'production' && secrets.RESEND_API_KEY_PRODUCTION || secrets.RESEND_API_KEY_STAGING }}
        TF_VAR_resend_from_email: ${{ secrets.RESEND_FROM_EMAIL }}
        TF_VAR_cookie_secret: ${{ inputs.deploy_environment == 'production' && secrets.COOKIE_SECRET_PRODUCTION || secrets.COOKIE_SECRET_STAGING }}
        TF_VAR_wechat_app_id: ${{ secrets.WECHAT_APP_ID }}
        TF_VAR_wechat_mch_id: ${{ secrets.WECHAT_MCH_ID }}
        TF_VAR_wechat_mch_api_v3_key: ${{ secrets.WECHAT_MCH_API_V3_KEY }}
        TF_VAR_wechat_mch_serial_no: ${{ secrets.WECHAT_MCH_SERIAL_NO }}
        TF_VAR_wechat_notify_url: ${{ inputs.deploy_environment == 'production' && secrets.WECHAT_NOTIFY_URL_PRODUCTION || secrets.WECHAT_NOTIFY_URL_STAGING }}
        TF_VAR_wechat_mch_private_key_base64: ${{ secrets.WECHAT_MCH_PRIVATE_KEY_BASE64 }}
        TF_VAR_wechat_pay_public_key_base64: ${{ secrets.WECHAT_PAY_PUBLIC_KEY_BASE64 }}
        TF_VAR_wechat_pay_public_key_id: ${{ secrets.WECHAT_PAY_PUBLIC_KEY_ID }}
        TF_VAR_wechat_platform_cert_base64: ${{ secrets.WECHAT_PLATFORM_CERT_BASE64 }}
        TF_VAR_wechat_platform_cert_serial_no: ${{ secrets.WECHAT_PLATFORM_CERT_SERIAL_NO }}
      run: terraform plan -input=false -no-color

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ !inputs.plan_only }}
    needs: [terraform-plan]
    environment: ${{ inputs.deploy_environment }}
    concurrency: 
      group: deploy-${{ inputs.deploy_environment }}
      cancel-in-progress: false
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.source_repo || github.repository }}
        ref: ${{ inputs.source_ref || github.sha }}
        token: ${{ github.token }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init \
          -backend-config="bucket=simple-relay-${{ inputs.deploy_environment }}" \
          -backend-config="prefix=terraform-state"

    - name: Terraform Apply
      working-directory: ${{ inputs.terraform_directory }}
      env:
        TF_VAR_api_base_url: ${{ secrets.API_BASE_URL }}
        TF_VAR_official_base_url: ${{ secrets.OFFICIAL_BASE_URL }}
        TF_VAR_image_tag: ${{ inputs.image_tag }}
        TF_VAR_service_name: simple-relay
        TF_VAR_billing_service_name: simple-relay-billing
        TF_VAR_frontend_service_name: simple-relay-frontend
        TF_VAR_outbound_service_1_name: simple-relay-outbound-1
        TF_VAR_outbound_service_2_name: simple-relay-outbound-2
        TF_VAR_firestore_database_name: simple-relay-db
        TF_VAR_deploy_environment: ${{ inputs.deploy_environment }}
        TF_VAR_api_secret_key: ${{ secrets.API_SECRET_KEY }}
        TF_VAR_resend_api_key: ${{ inputs.deploy_environment == 'production' && secrets.RESEND_API_KEY_PRODUCTION || secrets.RESEND_API_KEY_STAGING }}
        TF_VAR_resend_from_email: ${{ secrets.RESEND_FROM_EMAIL }}
        TF_VAR_cookie_secret: ${{ inputs.deploy_environment == 'production' && secrets.COOKIE_SECRET_PRODUCTION || secrets.COOKIE_SECRET_STAGING }}
        TF_VAR_wechat_app_id: ${{ secrets.WECHAT_APP_ID }}
        TF_VAR_wechat_mch_id: ${{ secrets.WECHAT_MCH_ID }}
        TF_VAR_wechat_mch_api_v3_key: ${{ secrets.WECHAT_MCH_API_V3_KEY }}
        TF_VAR_wechat_mch_serial_no: ${{ secrets.WECHAT_MCH_SERIAL_NO }}
        TF_VAR_wechat_notify_url: ${{ inputs.deploy_environment == 'production' && secrets.WECHAT_NOTIFY_URL_PRODUCTION || secrets.WECHAT_NOTIFY_URL_STAGING }}
        TF_VAR_wechat_mch_private_key_base64: ${{ secrets.WECHAT_MCH_PRIVATE_KEY_BASE64 }}
        TF_VAR_wechat_pay_public_key_base64: ${{ secrets.WECHAT_PAY_PUBLIC_KEY_BASE64 }}
        TF_VAR_wechat_pay_public_key_id: ${{ secrets.WECHAT_PAY_PUBLIC_KEY_ID }}
        TF_VAR_wechat_platform_cert_base64: ${{ secrets.WECHAT_PLATFORM_CERT_BASE64 }}
        TF_VAR_wechat_platform_cert_serial_no: ${{ secrets.WECHAT_PLATFORM_CERT_SERIAL_NO }}
      run: terraform apply -input=false -auto-approve -no-color

